### PR TITLE
Simplify recommended hbase-site.xml

### PR DESCRIPTION
**Pull request by bruceadams**
Adjust the OpenTSDB recommendation to match the hbase documentation.
The OpenTSDB recommended `hbase-site.xml` didn't work with hbase-0.95.
http://hbase.apache.org/book/quickstart.html suggests a much shorter
`hbase-site.xml`.

I have, just now, filed an OpenTSDB Contributor License Agreement.
- Bruce

### CODE REVIEW

**Comment by tsuna** [comment]
Hi Bruce,
what didn't work exactly?

I suppose you meant "hbase-0.90.5" and not "hbase-0.95", right?

I haven't tried HBase 0.90.5 yet, I think I should update the site to recommend HBase 0.92.2, as it is the preferred version for all new installs.

**Comment by bruceadams** [comment]
Oops! Sorry. I'm running hbase-0.92.1. Below is the end of the hbase log for the failed startup. (I tried the startup twice.) Shortening the hbase-site.xml file let me start hbase.

2012-05-16 05:26:28,410 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.dir=/opt/hbase-0.92.1  
2012-05-16 05:26:28,458 INFO org.apache.zookeeper.server.ZooKeeperServer: Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /tmp/hbase-adams/zookeeper/zookeeper_0/\
version-2 snapdir /tmp/hbase-adams/zookeeper/zookeeper_0/version-2  
2012-05-16 05:26:28,563 INFO org.apache.zookeeper.server.NIOServerCnxnFactory: binding to port 0.0.0.0/0.0.0.0:2181  
2012-05-16 05:26:28,585 INFO org.apache.zookeeper.server.persistence.FileTxnSnapLog: Snapshotting: 0x0 to /tmp/hbase-adams/zookeeper/zookeeper_0/version-2/snapshot.0  
2012-05-16 05:26:28,915 INFO org.apache.zookeeper.server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:57991  
2012-05-16 05:26:28,940 INFO org.apache.zookeeper.server.NIOServerCnxn: Processing stat command from /127.0.0.1:57991  
2012-05-16 05:26:28,952 INFO org.apache.zookeeper.server.NIOServerCnxn: Stat command output  
2012-05-16 05:26:28,952 INFO org.apache.zookeeper.server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:57991 (no session established for client)  
2012-05-16 05:26:28,952 INFO org.apache.hadoop.hbase.zookeeper.MiniZooKeeperCluster: Started MiniZK Cluster and connect 1 ZK server on client port: 2181  
2012-05-16 05:26:29,025 DEBUG org.apache.hadoop.hbase.master.HMaster: Set serverside HConnection retries=100  
2012-05-16 05:26:29,109 ERROR org.apache.hadoop.hbase.master.HMasterCommandLine: Failed to start master  
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster  
        at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:157)  
        at org.apache.hadoop.hbase.LocalHBaseCluster.addMaster(LocalHBaseCluster.java:198)  
        at org.apache.hadoop.hbase.LocalHBaseCluster.<init>(LocalHBaseCluster.java:148)  
        at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:138)  
        at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:103)  
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)  
        at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:76)  
        at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:1637)  
Caused by: java.lang.IllegalArgumentException: Failed resolve of null  
        at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:240)  
        at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.<init>(HMasterCommandLine.java:213)  
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)  
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)  
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)  
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)  
        at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:154)  
        ... 7 more

**Comment by bruceadams** [comment]
I should mention that I just learned about OpenTSDB yesterday. This was my first attempt as using it. I'm very excited about it. It look truly great!

**Comment by tsuna** [comment]
This error is really weird: `Failed resolve of null` – and totally uninformative.  Awesome.

Looking at [the code](https://github.com/apache/hbase/blob/0.92.1/src/main/java/org/apache/hadoop/hbase/master/HMaster.java#L240):

``` java
    // Server to handle client requests.
    String hostname = DNS.getDefaultHost(
      conf.get("hbase.master.dns.interface", "default"),
      conf.get("hbase.master.dns.nameserver", "default"));
    int port = conf.getInt(HConstants.MASTER_PORT, HConstants.DEFAULT_MASTER_PORT);
    // Creation of a HSA will force a resolve.
    InetSocketAddress initialIsa = new InetSocketAddress(hostname, port);
    if (initialIsa.getAddress() == null) {
      throw new IllegalArgumentException("Failed resolve of " + this.isa);
    }
```

So the error message is useless because they use `this.isa`, which hasn't been initialized yet.  They should do `+ initialIsa` instead.  I'll ping an HBase dev to fix the error message.

In the mean time, you need to figure out what `hostname` is set to, and why it doesn't resolve.  OpenTSDB's instructions are working for me, and they're the recommended way of setting up a single-node HBase instance.

**Comment by saintstack** [comment]
It's like this in 0.92 tip, 0.94, and trunk:

``` java
    // Server to handle client requests.
    String hostname = Strings.domainNamePointerToHostName(DNS.getDefaultHost(
      conf.get("hbase.master.dns.interface", "default"),
      conf.get("hbase.master.dns.nameserver", "default")));
    int port = conf.getInt(HConstants.MASTER_PORT, HConstants.DEFAULT_MASTER_PORT);
    // Creation of a HSA will force a resolve.
    InetSocketAddress initialIsa = new InetSocketAddress(hostname, port);
    if (initialIsa.getAddress() == null) {
      throw new IllegalArgumentException("Failed resolve of " + this.isa);
    }
```

I see that in 0.92.1 its as you say.

I'm about to roll a 0.92.2 RC. It'll have the fix.  Sorry for the inconvenience.

**Comment by tsuna** [comment]
Closing as won't fix.

**Pull request closed without merging**
